config/routes.rb
Rails.application.routes.draw do
  resources :recreation_types
  resources :campu_types
  resources :academic_types
  devise_for :users, :skip => [:registrations]
  resources :school_academics
  resources :school_campus
  resources :school_recreations
  resources :schools do
    collection do
      get :compare
    end
  end
  resources :campus
  resources :recreations
  resources :academics
  get 's_academics/:academic', to: 'schools#index', as: "s_academic"

  root 'schools#index'
  resources :cities
  resources :provinces

  get 'admin/panel'
  get '/admin' => 'admin#panel'

end

app/models/recreation.rb
class Recreation < ActiveRecord::Base
	TYPE = [ 'Interscholastic Sports', 'Recreational Sports', 'Arts' ]
	has_many :school_recreations
	has_many :schools, through: :school_recreations
	belongs_to :recreation_type
end

app/models/recreation_type.rb
class RecreationType < ActiveRecord::Base
	has_many :recreations
	has_many :school_recreations, through: :recreations
end

app/controllers/recreations_controller.rb
class RecreationsController < ApplicationController
  before_action :set_recreation, only: [:show, :edit, :update, :destroy]

  # GET /recreations
  # GET /recreations.json
  def index
    @recreations = Recreation.all
  end

  # GET /recreations/1
  # GET /recreations/1.json
  def show
  end

  # GET /recreations/new
  def new
    @recreation = Recreation.new
  end

  # GET /recreations/1/edit
  def edit
  end

  # POST /recreations
  # POST /recreations.json
  def create
    @recreation = Recreation.new(recreation_params)

    respond_to do |format|
      if @recreation.save
        format.html { redirect_to admin_path, notice: 'Recreation was successfully created.' }
        format.json { render :show, status: :created, location: @recreation }
      else
        format.html { render :new }
        format.json { render json: @recreation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /recreations/1
  # PATCH/PUT /recreations/1.json
  def update
    respond_to do |format|
      if @recreation.update(recreation_params)
        format.html { redirect_to admin_path, notice: 'Recreation was successfully updated.' }
        format.json { render :show, status: :ok, location: @recreation }
      else
        format.html { render :edit }
        format.json { render json: @recreation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /recreations/1
  # DELETE /recreations/1.json
  def destroy
    @recreation.destroy
    respond_to do |format|
      format.html { redirect_to admin_path, notice: 'Recreation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recreation
      @recreation = Recreation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recreation_params
      params.require(:recreation).permit(:recreation_type, :activity, :recreation_type_id)
    end
end

app/helpers/recreations_helper.rb
module RecreationsHelper
end

app/views/recreations/_form.html.erb
<%= form_for(@recreation) do |f| %>
  <% if @recreation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@recreation.errors.count, "error") %> prohibited this recreation from being saved:</h2>

      <ul>
      <% @recreation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="block">
      <div class="field">
        <%= f.label :activity %><br>
        <%= f.text_field :activity %>
      </div>
      <div class="field">
        <%= f.label :recreation_type %><br>
        <%= f.collection_select :recreation_type_id, RecreationType.all, :id, :name %>
      </div>
      <div class="actions recreation_submit">
        <%= f.submit %>
      </div>
    </div>
 
<% end %>

app/views/recreations/_index.html.erb
<table class="admin-table">
  <thead>
    <tr>
      <th>Used</th>
      <th>Type</th>
      <th>Activity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recreations.each do |recreation| %>
      <tr>
        <td><%= SchoolRecreation.where(recreation_id: recreation.id).count%> times</td>
        <td><%= recreation.recreation_type %></td>
        <td><%= recreation.activity %></td>
        <td><%= link_to 'Edit', edit_recreation_path(recreation) %></td>
        <td><% if SchoolRecreation.where(recreation_id: recreation.id).count == 0 %>
          <%= link_to 'Destroy', recreation, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
          </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/recreations/edit.html.erb
<div class="container">
	<h1>Editing Recreation</h1>

	<%= render 'form' %>

	<%= link_to "Back", :back %>
</div>	

app/views/recreations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Recreations</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Activity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @recreations.each do |recreation| %>
      <tr>
        <td><%= recreation.recreation_type %></td>
        <td><%= recreation.activity %></td>
        <td><%= link_to 'Show', recreation %></td>
        <td><%= link_to 'Edit', edit_recreation_path(recreation) %></td>
        <td><%= link_to 'Destroy', recreation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Recreation', new_recreation_path %>

app/views/recreations/new.html.erb
<div class="container">
	<h1>New Recreation</h1>

	<%= render 'form' %>

	<%= link_to 'Back', recreations_path %>
</div>

app/views/recreations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @recreation.recreation_type %>
</p>

<p>
  <strong>Activity:</strong>
  <%= @recreation.activity %>
</p>

<%= link_to 'Edit', edit_recreation_path(@recreation) %> |
<%= link_to 'Back', recreations_path %>