config/routes.rb
Rails.application.routes.draw do
  resources :recreation_types
  resources :campu_types
  resources :academic_types
  devise_for :users, :skip => [:registrations]
  resources :school_academics
  resources :school_campus
  resources :school_recreations
  resources :schools do
    collection do
      get :compare
    end
  end
  resources :campus
  resources :recreations
  resources :academics
  get 's_academics/:academic', to: 'schools#index', as: "s_academic"

  root 'schools#index'
  resources :cities
  resources :provinces

  get 'admin/panel'
  get '/admin' => 'admin#panel'

end

app/models/campu.rb
class Campu < ActiveRecord::Base
	TYPE = [ 'Student Life', 'Dorm Amenities', 'Facilities', 'Clubs & Organizations' ]
	has_many :school_campus
	has_many :schools, through: :school_campus
	belongs_to :campu_type
end

app/models/campu_type.rb
class CampuType < ActiveRecord::Base
	has_many :campus
	has_many :school_campus, through: :campus
end

app/controllers/campus_controller.rb
class CampusController < ApplicationController
  before_action :set_campu, only: [:show, :edit, :update, :destroy]

  # GET /campus
  # GET /campus.json
  def index
    @campus = Campu.all
  end

  # GET /campus/1
  # GET /campus/1.json
  def show
  end

  # GET /campus/new
  def new
    @campu = Campu.new
  end

  # GET /campus/1/edit
  def edit
  end

  # POST /campus
  # POST /campus.json
  def create
    @campu = Campu.new(campu_params)

    respond_to do |format|
      if @campu.save
        format.html { redirect_to admin_path, notice: 'Campu was successfully created.' }
        format.json { render :show, status: :created, location: @campu }
      else
        format.html { render :new }
        format.json { render json: @campu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /campus/1
  # PATCH/PUT /campus/1.json
  def update
    respond_to do |format|
      if @campu.update(campu_params)
        format.html { redirect_to admin_path, notice: 'Campu was successfully updated.' }
        format.json { render :show, status: :ok, location: @campu }
      else
        format.html { render :edit }
        format.json { render json: @campu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /campus/1
  # DELETE /campus/1.json
  def destroy
    @campu.destroy
    respond_to do |format|
      format.html { redirect_to admin_path, notice: 'Campu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_campu
      @campu = Campu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def campu_params
      params.require(:campu).permit(:campu_type, :feature, :campu_type_id)
    end
end

app/helpers/campus_helper.rb
module CampusHelper
end

app/views/campus/_form.html.erb
<%= form_for(@campu) do |f| %>
  <% if @campu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@campu.errors.count, "error") %> prohibited this campu from being saved:</h2>

      <ul>
      <% @campu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="block">  
    <div class="field">
      <%= f.label :feature %><br>
      <%= f.text_area :feature %>
    </div>
    <div class="field">
      <%= f.label :type %><br>
      <%= f.collection_select :campu_type_id, CampuType.all, :id, :name %>
    </div>
    <div class="actions campu_submit">
      <%= f.submit 'Create Campus' %>
    </div>
  </div>
<% end %>

app/views/campus/_index.html.erb
<table class="admin-table">
  <thead>
    <tr>
      <th>Used</th>
      <th>Type</th>
      <th>Feature</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @campus.each do |campu| %>
      <tr>
        <td><%= SchoolCampu.where(campu_id: campu.id).count%> times</td>
        <td><%= campu.campu_type %></td>
        <td><%= campu.feature %></td>
        <td><%= link_to 'Edit', edit_campu_path(campu) %></td>
        <td><% if SchoolCampu.where(campu_id: campu.id).count == 0%>
          <%= link_to 'Destroy', campu, method: :delete, data: { confirm: 'Are you sure?' } %>
          <% end %>
          </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/campus/edit.html.erb
<h1>Editing Campus</h1>

<%= render 'form' %>

<%= link_to "Back", :back %>

app/views/campus/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Campus</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th>Feature</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @campus.each do |campu| %>
      <tr>
        <td><%= campu.campu_type %></td>
        <td><%= campu.feature %></td>
        <td><%= link_to 'Show', campu %></td>
        <td><%= link_to 'Edit', edit_campu_path(campu) %></td>
        <td><%= link_to 'Destroy', campu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Campu', new_campu_path %>

app/views/campus/new.html.erb
<h1>New Campu</h1>

<%= render 'form' %>

<%= link_to 'Back', campus_path %>

app/views/campus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Type:</strong>
  <%= @campu.campu_type %>
</p>

<p>
  <strong>Feature:</strong>
  <%= @campu.feature %>
</p>

<%= link_to 'Edit', edit_campu_path(@campu) %> |
<%= link_to 'Back', campus_path %>