config/routes.rb
Rails.application.routes.draw do
  resources :recreation_types
  resources :campu_types
  resources :academic_types
  devise_for :users, :skip => [:registrations]
  resources :school_academics
  resources :school_campus
  resources :school_recreations
  resources :schools do
    collection do
      get :compare
    end
  end
  resources :campus
  resources :recreations
  resources :academics
  get 's_academics/:academic', to: 'schools#index', as: "s_academic"

  root 'schools#index'
  resources :cities
  resources :provinces

  get 'admin/panel'
  get '/admin' => 'admin#panel'

end

app/models/school_campu.rb
class SchoolCampu < ActiveRecord::Base
	belongs_to :school
	belongs_to :campu
end

app/controllers/school_campus_controller.rb
class SchoolCampusController < ApplicationController
  before_action :set_school_campu, only: [:show, :edit, :update, :destroy]

  # GET /school_campus
  # GET /school_campus.json
  def index
    @school_campus = SchoolCampu.all
  end

  # GET /school_campus/1
  # GET /school_campus/1.json
  def show
  end

  # GET /school_campus/new
  def new
    @school_campu = SchoolCampu.new
    @campus = Campu.all
    @school = School.find(params[:school_id])
  end

  # GET /school_campus/1/edit
  def edit
    @campus = Campu.all
  end

  # POST /school_campus
  # POST /school_campus.json
  def create
    @school_campu = SchoolCampu.new(school_campu_params)
    @school_campu.school_id = params[:school_id]

    respond_to do |format|
      if @school_campu.save
        format.html { redirect_to edit_school_path(params[:school_id]), notice: 'School campu was successfully created.' }
        format.json { render :show, status: :created, location: @school_campu }
      else
        format.html { render :new }
        format.json { render json: @school_campu.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /school_campus/1
  # PATCH/PUT /school_campus/1.json
  def update
    respond_to do |format|
      if @school_campu.update(school_campu_params)
        format.html { redirect_to edit_school_path(params[:school_id]), notice: 'School campu was successfully updated.' }
        format.json { render :show, status: :ok, location: @school_campu }
      else
        format.html { render :edit }
        format.json { render json: @school_campu.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /school_campus/1
  # DELETE /school_campus/1.json
  def destroy
    @school = @school_campu.school
    @school_campu.destroy
    respond_to do |format|
      format.html { redirect_to edit_school_path(@school), notice: 'School campu was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school_campu
      @school_campu = SchoolCampu.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def school_campu_params
      params.require(:school_campu).permit(:school_id, :campu_id)
    end
end

app/helpers/school_campus_helper.rb
module SchoolCampusHelper
end

app/views/school_campus/_form.html.erb
<% if @school_campu.present? %>
<%= form_for(@school_campu) do |f| %>
  <% if @school_campu.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@school_campu.errors.count, "error") %> prohibited this school_campu from being saved:</h2>

      <ul>
      <% @school_campu.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="block">
     <div class="field">
       <%= f.label :campu_id, 'campus'  %><br>
       <%= f.collection_select :campu_id, @campus, :id, :feature %>
     </div>
    </div>  
   <div class="actions">
     <%= f.submit 'Create School campus' %>
     <%= hidden_field_tag :school_id, @school.id %>
   </div>
  
<% end %>
<% end %>

app/views/school_campus/edit.html.erb
<div class="container">
	<h1>Editing School Campu</h1>

	<%= render 'form' %>

	<%= link_to 'Show', @school_campu %> |
	<%= link_to 'Back', school_campus_path %>
</div>	

app/views/school_campus/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing School Campus</h1>

<table>
  <thead>
    <tr>
      <th>School</th>
      <th>Campu</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @school_campus.each do |school_campu| %>
      <tr>
        <td><%= school_campu.school %></td>
        <td><%= school_campu.campu %></td>
        <td><%= link_to 'Show', school_campu %></td>
        <td><%= link_to 'Edit', edit_school_campu_path(school_campu) %></td>
        <td><%= link_to 'Destroy', school_campu, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New School campu', new_school_campu_path %>

app/views/school_campus/new.html.erb
<div class="container">
	<h1>New School Campus</h1>

	<%= render 'form' %>

	<%= link_to 'Back', school_campus_path %>
</div>

app/views/school_campus/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>School:</strong>
  <%= @school_campu.school %>
</p>

<p>
  <strong>Campu:</strong>
  <%= @school_campu.campu %>
</p>

<%= link_to 'Edit', edit_school_campu_path(@school_campu) %> |
<%= link_to 'Back', school_campus_path %>